"""Render README.md from entries/. Use --check in CI to verify it is up to date."""
import sys
from pathlib import Path

from entry import load_entry

ROOT = Path(__file__).resolve().parent.parent
README_PATH = ROOT / "README.md"
ENTRIES_DIR = ROOT / "entries"

HEADER = """# bestie-skills

> **This file is auto-generated by `scripts/build_readme.py`. Do not edit by hand.**
> Edit entries in `entries/` and run `python scripts/build_readme.py`.

A community-curated, agent-agnostic catalog of useful AI-agent skills
(Claude Code, Codex, and more). We store **links and metadata only** — never a
copy of a skill's code. Each entry credits the original author, license, and source.

See [CONTRIBUTING.md](CONTRIBUTING.md) to add a skill. Licensed under MIT.

"""

CATEGORY_ORDER = ["coding", "research", "writing", "data", "devops", "workflow", "meta"]


def _row(fm):
    name = fm["name"]
    link = f"[{name}]({fm['source_url']})"
    agents = ", ".join(fm["agents"])
    tags = ", ".join(fm.get("tags", []))
    return (
        f"| {link} | {fm['summary']} | {agents} | {tags} | "
        f"`{fm['status']}` | `{fm['security']}` |"
    )


def render_readme(entries):
    """Return the full README markdown for a list of loaded entries."""
    by_cat = {}
    for entry in entries:
        fm = entry["frontmatter"]
        by_cat.setdefault(fm["category"], []).append(fm)

    parts = [HEADER]
    ordered = [c for c in CATEGORY_ORDER if c in by_cat]
    ordered += [c for c in sorted(by_cat) if c not in CATEGORY_ORDER]
    for cat in ordered:
        parts.append(f"## {cat}\n")
        parts.append("| Skill | Summary | Agents | Tags | Status | Security |")
        parts.append("| --- | --- | --- | --- | --- | --- |")
        for fm in sorted(by_cat[cat], key=lambda f: f["name"]):
            parts.append(_row(fm))
        parts.append("")

    tag_map = {}
    for entry in entries:
        fm = entry["frontmatter"]
        for tag in fm.get("tags", []):
            tag_map.setdefault(tag, []).append(fm)
    if tag_map:
        parts.append("## Browse by topic\n")
        for tag in sorted(tag_map):
            links = ", ".join(
                f"[{fm['name']}]({fm['source_url']})"
                for fm in sorted(tag_map[tag], key=lambda f: f["name"])
            )
            parts.append(f"- **{tag}** — {links}")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _load_all(entries_dir):
    return [load_entry(p) for p in sorted(Path(entries_dir).glob("*.md"))]


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    content = render_readme(_load_all(ENTRIES_DIR))
    if "--check" in argv:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != content:
            print("FAIL: README.md is stale. Run: python scripts/build_readme.py")
            return 1
        print("OK: README.md is up to date.")
        return 0
    README_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {README_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
